### ISSUE TITLE
load command too expensive with recources

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/messages-bundle#7]
The load command is too expensive on resources.

It uses the doctrine entity manager repository to get items and uses the entity manager persist flush actions each round on a foreach. This causes delays and memory exhaustion and slow processes.

To optimize this we can use the query builder of doctrine to insert or update when necessary. Listeners who listen to persist and flush are not called anymore. The unit of work is not calculated anymore. So Insert and update queries would make the load messages lightning fast.

**Comment by boudewijn-zicht** [comment]
Performance issues when loading all messages into the database have been fixed in version 2.5.4.
